Add some kind of docblocks and checks.

diff --git a/bin/lint-style b/bin/lint-style
--- a/bin/lint-style
+++ b/bin/lint-style
@@ -1,3 +1,17 @@
 #!/bin/sh
 
+###
+ # Lint Styles
+ #
+ # This will automatically find our SassLint configuration and lint against that.
+ #
+ # @since 1.0.0
+ # @author Aubrey Portwood <aubrey@webdevstudios.com>
+ ##
+
+if [[ -f "./node_modules/.bin/wp-scripts" ]]; then
+	echo "Cannot find @wordpress/scripts, is it installed?"
+	exit 1
+fi
+
 ./node_modules/.bin/wp-scripts lint-style
diff --git a/bin/packages-update b/bin/packages-update
--- a/bin/packages-update
+++ b/bin/packages-update
@@ -1,3 +1,17 @@
 #!/bin/sh
 
+###
+ # Update Packages
+ #
+ # Uses `@wordpress/scripts` wp-scripts package-update command.
+ #
+ # @since 1.0.0
+ # @author Aubrey Portwood <aubrey@webdevstudios.com>
+ ##
+
+if [[ -f "./node_modules/.bin/wp-scripts" ]]; then
+	echo "Cannot find @wordpress/scripts, is it installed?"
+	exit 1
+fi
+
 ./node_modules/.bin/wp-scripts packages-update
